import { Montserrat, Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const fontStyle = Montserrat({
  variable: "--font-style",
  subsets: ["latin"],
});

const fontText = Open_Sans({
  variable: "--font-text",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kawan Legal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fontStyle.variable} ${fontText.variable} font-text antialiased`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
